version: '3'

services:
  fastapi:
    container_name: fastapi_delivery
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8000:8000'
    env_file:
      - .env
    networks:
      - my_network
    depends_on:
      - db

  db:
    image: postgres
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./.postgres_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DOCKER_PORT}
    networks:
      - my_network

#  java_service:
#    build:
#      context: ./java_service
#    container_name: java_service
#    restart: always
#    ports:
#      - "8080:8080"
#    env_file:
#      - .env
#    depends_on:
#      - db
#    networks:
#      - my_network

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge
